name: learn-github-actions
on: [push]
jobs:
  env-var-tests:
    runs-on: ubuntu-latest
    env:
      ENV_DEFAULT_JSON_FILE: ".github/configs/env_default.json"

    steps:
      - uses: actions/checkout@v2
      
      - name: Set ENV_JSON_FILE
        run: echo "ENV_JSON_FILE=.github/configs/env_$GITHUB_ACTOR.json" >> $GITHUB_ENV

      - name: Check for env_<user>.json file
        id: check_file
        uses: andstor/file-existence-action@v1
        with:
          files: $ENV_JSON_FILE

      - name: Show output
        run: |
          echo "This is the default - $ENV_DEFAULT_JSON_FILE"
          echo "This is the actor - $ENV_JSON_FILE"
             
#       - name
#       - name: JSON to variables
#         uses: antifree/json-to-variables@v1.0.1
#         with:
#           filename: '.github/configs/test.json'
#           prefix: test
#           
      - name: Show output 2
        run: |
          echo "This is the ${{ env.test_value }}"
          echo "This is $GITHUB_ACTOR"

#   check-bats-version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - run: npm install -g bats
#       - run: bats -v
